import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import Footer from "./components/Footer";
import Header from "./components/Header";
import SideBar from "./components/SideBar";
import "./globals.css";

export const metadata = {
  title: "Enzo Ingraito · Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <head>
        <link rel="icon" href="/images/favicon.webp" sizes="any" />
      </head>
      <body>
        <SideBar social={true} />
        <SideBar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
